trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.5.7'

steps:
- task: UseTerraform@0
  inputs:
    terraformVersion: $(TF_VERSION)

- script: |
    terraform init
    terraform validate
    terraform plan -out=tfplan
  displayName: 'Terraform Init & Plan'

- task: ManualValidation@0
  inputs:
    instructions: 'Review Terraform plan in the logs and apply manually if approved.'
    onTimeout: 'reject'
    timeout: '1h'
