trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update && sudo apt-get install -y unzip curl
    curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
    unzip terraform.zip
    sudo mv terraform /usr/local/bin/
    terraform version
  displayName: 'Install Terraform CLI'

- script: |
    terraform init
    terraform validate
    terraform plan -out=tfplan
  displayName: 'Terraform Init & Plan'

- script: |
    echo "Manual approval step simulated."
    echo "Waiting 60 seconds as a placeholder..."
    sleep 60
  displayName: 'Simulate Manual Approval Step'

# You can uncomment this for real apply
# - script: terraform apply tfplan
#   displayName: 'Terraform Apply'
